FROM redmine:4.0

# プラグインのコピー
COPY ./plugins /usr/src/redmine/plugins

# テーマのコピー
COPY ./themes /usr/src/redmine/public/themes

# configurationファイルのコピー
COPY ./config/configuration.yml /usr/src/redmine/config/

